# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\x12\x03\x61pp\"\xcf\x01\n\x13MsgDelivery_request\x12&\n\x0eoperation_type\x18\x01 \x01(\x0e\x32\x0e.app.Operation\x12 \n\x0bsource_type\x18\x02 \x01(\x0e\x32\x0b.app.Source\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\x12\x15\n\rlast_write_id\x18\x06 \x01(\x05\x12\x19\n\x11last_write_branch\x18\x07 \x01(\x05\x12\x11\n\twrite_set\x18\x08 \x01(\t\"\xa1\x01\n\x14MsgDelivery_response\x12%\n\x10operation_result\x18\x01 \x01(\x0e\x32\x0b.app.Result\x12 \n\x0bsource_type\x18\x02 \x01(\x0e\x32\x0b.app.Source\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\x12\x15\n\rlast_write_id\x18\x06 \x01(\x05*1\n\tOperation\x12\t\n\x05query\x10\x00\x12\x0c\n\x08withdraw\x10\x01\x12\x0b\n\x07\x64\x65posit\x10\x02*-\n\x06Result\x12\x0b\n\x07success\x10\x00\x12\x0b\n\x07\x66\x61ilure\x10\x01\x12\t\n\x05\x65rror\x10\x02*\"\n\x06Source\x12\x0c\n\x08\x63ustomer\x10\x00\x12\n\n\x06\x62ranch\x10\x01\x32L\n\x04\x42\x61nk\x12\x44\n\x0bMsgDelivery\x12\x18.app.MsgDelivery_request\x1a\x19.app.MsgDelivery_response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATION._serialized_start=393
  _OPERATION._serialized_end=442
  _RESULT._serialized_start=444
  _RESULT._serialized_end=489
  _SOURCE._serialized_start=491
  _SOURCE._serialized_end=525
  _MSGDELIVERY_REQUEST._serialized_start=20
  _MSGDELIVERY_REQUEST._serialized_end=227
  _MSGDELIVERY_RESPONSE._serialized_start=230
  _MSGDELIVERY_RESPONSE._serialized_end=391
  _BANK._serialized_start=527
  _BANK._serialized_end=603
# @@protoc_insertion_point(module_scope)
