# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bank_pb2 as bank__pb2


class BankStub(object):
    """The Bank service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MsgDelivery = channel.unary_unary(
                '/app.Bank/MsgDelivery',
                request_serializer=bank__pb2.MsgDelivery_request.SerializeToString,
                response_deserializer=bank__pb2.MsgDelivery_response.FromString,
                )


class BankServicer(object):
    """The Bank service definition.
    """

    def MsgDelivery(self, request, context):
        """Service between Branch and Customer, Branch and Branch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MsgDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.MsgDelivery,
                    request_deserializer=bank__pb2.MsgDelivery_request.FromString,
                    response_serializer=bank__pb2.MsgDelivery_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.Bank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bank(object):
    """The Bank service definition.
    """

    @staticmethod
    def MsgDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.Bank/MsgDelivery',
            bank__pb2.MsgDelivery_request.SerializeToString,
            bank__pb2.MsgDelivery_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
